
// maps file extensions supported by Jupytext's --set-formats to their
// respective Jupyter kernelspec kernel languages. lots of blanks that
// I don't know, please PR if you need support
export const EXTENSION_FORMATS = {
    'ipynb': null,
    'md': null,
    'markdown': null,
    'Rmd': null,
    'py': 'python',
    'coco': null,
    'R': null,
    'r': null,
    'jl': 'julia',
    'cpp': null,
    'ss': null,
    'clj': null,
    'scm': null,
    'sh': null,
    'ps1': null,
    'q': null,
    'm': null,
    'wolfram': null,
    'pro': null,
    'js': null,
    'ts': null,
    'scala': null,
    'rs': null,
    'robot': null,
    'resource': null,
    'cs': null,
    'fsx': null,
    'fs': null,
    'sos': null,
    'java': null,
    'groovy': null,
    'sage': null,
    'ml': null,
    'hs': null,
    'tcl': null,
    'mac': null,
    'gp': null,
    'do': null,
    'sas': null,
    'xsh': null,
    'lua': null,
    'go': null,
    'qmd': null,
    'myst': null,
    'mystnb': null,
    'mnb': null,
    'auto': null
};